# Generated by Django 4.2.6 on 2023-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributor_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
