version: "3.8"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./data:/app/data

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./static:/usr/share/nginx/html/static/
      - /etc/letsencrypt/live/nasa-hackathon.tnbswap.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/nasa-hackathon.tnbswap.com/privkey.pem:/etc/nginx/certs/privkey.pem

volumes:
  sqlite-data:
